#---- https://evertpot.com/osx-tmux-vim-copy-paste-clipboard/ ----

# extend buffer limit (scrolling)
set-option -g history-limit 99999

# mac copy-paste integration
set-option -g default-command "reattach-to-user-namespace -l bash"

# Use vim keybindings in copy mode
setw -g mode-keys vi

#Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# Update default binding of `Enter` to be also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

#Bind ']' to use pbpaste
bind ] run "reattach-to-user-namespace pbpaste | tmux load-buffer - && tmux paste-buffer"
#------------------

# use default shell (in the case of OSX Catelina this now means ZSH)
set-option -g default-command "reattach-to-user-namespace -l zsh"
#set-option -g default-shell /bin/zsh

# Left/Right not working for some reason :shrug:
#bind -r C-Left resize-pane -R
#bind -r C-Right resize-pane -L

# Left/Right resize of pane with ctrl+j ctrl+k
bind -r C-j resize-pane -L
bind -r C-k resize-pane -R

